name: cron
schedule:
  cron: "0 * * * *"
jobs:
  env:
    POSTGRES_HOST: ${{ secrets.PostgresHost }}
    POSTGRES_USER: ${{ secrets.PostgresUser }}
    POSTGRES_PASSWORD: ${{ secrets.PostgresPassword }}
    POSTGRES_DB: ${{ secrets.PostgresDB }}
    POSTGRES_PORT: ${{ secrets.PostgresPort}}
  steps:
    - name: Build
      run: cargo build --verbose
    - name: Run
      run: cargo run --verbose
