name: shell_task_cron
schedule:
  type: cron
  cron: "*/1 * * * *"
  priority: 5
  lables:
    - linux
jobs:
  env:
    TASKTYPE: shell
    SCHEDULETYPE: cron
  steps:
    - name: run
      run: echo task:$TASKTYPE, schedule:$SCHEDULETYPE
