// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package tasks

import (
	context "context"
	utils "github.com/silverswords/scheduler/api/utils"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StateChangeClient is the client API for StateChange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateChangeClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*utils.Empty, error)
	Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*utils.Empty, error)
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*utils.Empty, error)
}

type stateChangeClient struct {
	cc grpc.ClientConnInterface
}

func NewStateChangeClient(cc grpc.ClientConnInterface) StateChangeClient {
	return &stateChangeClient{cc}
}

func (c *stateChangeClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*utils.Empty, error) {
	out := new(utils.Empty)
	err := c.cc.Invoke(ctx, "/scheduler.tasks.StateChange/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateChangeClient) Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*utils.Empty, error) {
	out := new(utils.Empty)
	err := c.cc.Invoke(ctx, "/scheduler.tasks.StateChange/Fail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateChangeClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*utils.Empty, error) {
	out := new(utils.Empty)
	err := c.cc.Invoke(ctx, "/scheduler.tasks.StateChange/Complete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateChangeServer is the server API for StateChange service.
// All implementations must embed UnimplementedStateChangeServer
// for forward compatibility
type StateChangeServer interface {
	Start(context.Context, *StartRequest) (*utils.Empty, error)
	Fail(context.Context, *FailRequest) (*utils.Empty, error)
	Complete(context.Context, *CompleteRequest) (*utils.Empty, error)
	mustEmbedUnimplementedStateChangeServer()
}

// UnimplementedStateChangeServer must be embedded to have forward compatible implementations.
type UnimplementedStateChangeServer struct {
}

func (UnimplementedStateChangeServer) Start(context.Context, *StartRequest) (*utils.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedStateChangeServer) Fail(context.Context, *FailRequest) (*utils.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fail not implemented")
}
func (UnimplementedStateChangeServer) Complete(context.Context, *CompleteRequest) (*utils.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedStateChangeServer) mustEmbedUnimplementedStateChangeServer() {}

// UnsafeStateChangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateChangeServer will
// result in compilation errors.
type UnsafeStateChangeServer interface {
	mustEmbedUnimplementedStateChangeServer()
}

func RegisterStateChangeServer(s grpc.ServiceRegistrar, srv StateChangeServer) {
	s.RegisterService(&StateChange_ServiceDesc, srv)
}

func _StateChange_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateChangeServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.tasks.StateChange/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateChangeServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateChange_Fail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateChangeServer).Fail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.tasks.StateChange/Fail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateChangeServer).Fail(ctx, req.(*FailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateChange_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateChangeServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.tasks.StateChange/Complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateChangeServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StateChange_ServiceDesc is the grpc.ServiceDesc for StateChange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateChange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.tasks.StateChange",
	HandlerType: (*StateChangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _StateChange_Start_Handler,
		},
		{
			MethodName: "Fail",
			Handler:    _StateChange_Fail_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _StateChange_Complete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tasks/tasks.proto",
}
